add more informative error for GHA

diff --git a/.github/workflows/validate-config.yaml b/.github/workflows/validate-config.yaml
--- a/.github/workflows/validate-config.yaml
+++ b/.github/workflows/validate-config.yaml
@@ -55,16 +55,19 @@ jobs:
             cat(gt::as_raw_html(tbl), "\n", file = diff, sep = "", append = TRUE)
           } else {
             cat("result=true", "\n", file = output, sep = "", append = TRUE)
+            writeLines(":white_check_mark: all checks passed\n", diff)
           }
         shell: Rscript {0}
       - name: "Comment on PR"
         id: comment-diff
-        if: ${{ github.event_name != 'workflow_dispatch' && steps.validate.outputs.result == 'false' }}
+        if: ${{ github.event_name != 'workflow_dispatch' }}
         uses: carpentries/actions/comment-diff@main
         with:
           pr: ${{ env.PR_NUMBER }}
           path: ${{ env.DIFF_PATH }}
       - name: Error on Failure
         if: ${{ steps.validate.outputs.result == 'false' }}
-        run: exit 1
+        run: |
+          echo "::error title=Invalid Configuration::Errors were detected in one or more config files in `hub-config/`."
+          exit 1
 
